pipeline {
    agent {
        docker {
            image 'python:3.11'
        }
    }

    stages {

        stage('Install Dependencies') {
            steps {
                sh 'pip install -r lesson_29/requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'pytest lesson_29/tests --alluredir=lesson_29/allure-results'
            }
        }

        stage('Archive Results') {
            steps {
                archiveArtifacts artifacts: 'lesson_29/allure-results/**', fingerprint: true
            }
        }
    }
}