pipeline {
    agent any

    stages {

        stage('Install Python') {
            steps {
                sh '''
                apt update
                apt install -y python3 python3-pip
                '''
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'pip3 install -r lesson_29/requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'pytest lesson_29/tests --alluredir=lesson_29/allure-results'
            }
        }

        stage('Archive Results') {
            steps {
                archiveArtifacts artifacts: 'lesson_29/allure-results/**', fingerprint: true
            }
        }
    }
}